version: '2'

services:
  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin'
    restart: always
    ports:
       - '8180:80'
    links:
        - mysql:mysql
    environment:
        MYSQL_USER: temp
        MYSQL_PASSWORD: temppassword
        MYSQL_ROOT_PASSWORD: rootpassword
        PMA_HOST: mysql

  mysql:
    image: 'mariadb'
    ports:
        - '3306:3306'
    volumes:
      - my-datavolume:/var/lib/mysql
    environment:
        MYSQL_USER: temp
        MYSQL_PASSWORD: temppassword
        MYSQL_ROOT_PASSWORD: rootpassword
        MYSQL_DATABASE: tempdb
volumes:
  my-datavolume: