phpmyadmin:
    image: 'phpmyadmin/phpmyadmin'
    restart: always
    ports:
       - '8180:80'
    links:
        - mysql:mysql
    environment:
        MYSQL_USER: tempuser
        MYSQL_PASSWORD: temppassword
        MYSQL_ROOT_PASSWORD: rootpassword
        PMA_HOST: mysql

mysql:
    image: 'mariadb'
    ports:
        - '3306:3306'
    volumes:
        - ./db_data:/var/lib/mysql
        - ./extra_data:/extra_data
    environment:
        MYSQL_USER: tempuser
        MYSQL_PASSWORD: temppassword
        MYSQL_ROOT_PASSWORD: rootpassword
        MYSQL_DATABASE: tempdb